### ISSUE TITLE
py3 support

### ISSUE THREAD

**Issue by deanmalmgren** [ankushshah89/python-docx2txt#11]
Hey @ankushshah89! Thanks again for putting this together for `textract` and others :)

I recently setup `pyup` and realized that [`docx2txt` isn't py3 compatible](https://pyup.io/account/repos/github/deanmalmgren/textract/). I'm not sure what would be involved here, but I thought I'd mention it so its on your radar.

**Comment by ankushshah89** [comment]
i thought it was py3 compatible, I will double check though. The link you attached to "docx2txt isn't py3 compatible" doesn't work.

**Comment by deanmalmgren** [comment]
You're probably right. I seem to recall it was py3 compatible as well. I'm not sure how pyup detects these sorts of things, but here's a screenshot of the site

<img width="640" alt="screen shot 2017-03-30 at 8 11 49 am" src="https://cloud.githubusercontent.com/assets/255672/24505745/a7f7a592-1520-11e7-9aca-f5b545de3a85.png">

**Comment by cyinwei** [comment]
Hey, when running the 0.6 version from `pip`, I encountered two runtime errors when trying to extract the images (on Python 3.6.3).  Both errors are python 2->3 ones.

- One was the image -> binary ('b) error that @gonzocoder fixed with #14.
- The other was printing to `stdout`, which now takes `str` rather than `bytes`.  #19 should fix that.

Can you update the release when you get the chance?  Thank you.

**Comment by ankushshah89** [comment]
I just released a new version on [pypi](https://pypi.python.org/pypi?%3Aaction=pkg_edit&name=docx2txt ) which includes the image -> binary bug (https://github.com/ankushshah89/python-docx2txt/pull/14)

I left some comment for the https://github.com/ankushshah89/python-docx2txt/pull/19 and waiting for an updated PR. Thanks!

**Comment by jamesacampbell** [comment]
Please add python3 support. Getting `File "/usr/local/bin/docx2txt", line 9, in <module>
    sys.stdout.write(text.encode('utf-8'))
TypeError: write() argument must be str, not bytes`

**Comment by ankushshah89** [comment]
Released a [new version (0.8)](https://pypi.org/project/docx2txt/) with py3 support.
