### ISSUE TITLE
extract Images?

### ISSUE THREAD

**Issue by lxj0276** [ankushshah89/python-docx2txt#13]
I find the code is wrong in docx2txt.py,line 103 write image file should use "wb",not "w"

**Comment by liangsijian** [comment]
@lxj0276 It work well on Linux not Win32, in Win3 should use "wb"

**Comment by ankushshah89** [comment]
It should be fixed with https://github.com/ankushshah89/python-docx2txt/commit/509158efc88835ff530236b83394af96233aba63
