### ISSUE TITLE
Don't work how I expected

### ISSUE THREAD

**Issue by juniordiasjfd** [ankushshah89/python-docx2txt#17]
Hi,

I'm trying extract a text from a file file.docx (in attachment) with python-docx2txt, but him don't work how I expected.
[file.docx](https://github.com/ankushshah89/python-docx2txt/files/1432733/file.docx)
I created a .py file in a /folder directory with a following code:

import docx2txt
TEXT = docx2txt.process("file.docx", "/tmp/img_dir") 

I expected a new directory /folder/tmp/img_dir with a pictures from file.docx after run the code.
But I obtained only the text from file.docx in the variable TEXT.

Where did I go wrong?

**Comment by ankushshah89** [comment]
There is nothing wrong in your code. The picture in your doc is actually a WordArt which currently aren't extracted. You can try with inserting actual image and try with that.

**Comment by juniordiasjfd** [comment]
Thank you for your answer.

I tried run again with the suggested modifications (pictures in JPEG), but have following feedback:

Traceback (most recent call last):
  File "C:\Users\junio\Desktop\python_extract_word\teste.py", line 7, in <module>
    text = docx2txt.process("file.docx", "/tmp/img_dir")
  File "C:\Users\junio\AppData\Local\Programs\Python\Python36-32\lib\site-packages\docx2txt\docx2txt.py", line 104, in process
    dst_f.write(zipf.read(fname))
TypeError: write() argument must be str, not bytes

**Comment by golimarrrr** [comment]
I got that error with python3 but worked fine with python2

**Comment by ankushshah89** [comment]
I just released a new version and now it should work with Python3 too. Please update.
