### ISSUE TITLE
Is this a working application?

### ISSUE THREAD

**Issue by GarrettHartley** [ankushshah89/python-docx2txt#3]
text = docx2txt.process("kindergarten--letter-sound-association--b--baby-black-bat--lesson-plan.docx", "/tmp/img_dir")

I run this line of code and the program runs, but an output document is not created and the images are not saved in a folder '/temp/img_dir'

**Comment by ankushshah89** [comment]
Its a working application. What do you mean by document is not created? The "text" variable was empty after the call? Can you share the file so I can debug?

**Comment by GarrettHartley** [comment]
I see, it is working properly. I thought it was going to create a file with the text in it, not just create variable. Thanks.

**Comment by ankushshah89** [comment]
okay..closing issue.
