### ISSUE TITLE
Error on print

### ISSUE THREAD

**Issue by MannyGrewal** [ankushshah89/python-docx2txt#5]
There is a minor error when using Python 3.5

the print statements are missing ( ), so the compiler complains.

I fixed them like this

print('File %s do not exist.' % (args.docx))

**Comment by ankushshah89** [comment]
thanks for reporting but [this](https://github.com/ankushshah89/python-docx2txt/blob/master/docx2txt/docx2txt.py#L25) already have the brackets. Can you check again? I hope you are using the latest version.

**Comment by MannyGrewal** [comment]
I just did pip install today and the version I got didn't have ( ) in the print statement. Not a big issues, overall the tool is great. 

May be the version that pip install pulls is not latest or something like that.

**Comment by ankushshah89** [comment]
Ah right, I didn't push the latest version on pip. The one on pip is still works only for python2.7 because of print statements.

**Comment by MannyGrewal** [comment]
Oh ok, you can close the issue then. cheers.

**Comment by ankushshah89** [comment]
Released the new python version on pip, making it compatible with python3.x
