### ISSUE TITLE
text = docx2txt.process("file.docx", "/tmp/img_dir")  Function not working

### ISSUE THREAD

**Issue by GarrettHartley** [ankushshah89/python-docx2txt#6]
I have the following python script

import docx2txt

text = docx2txt.process("first-grade--consonants-and-digraphs--ng--king-who-swings--lesson-plan.docx", "/imgs") 

From your description I would expect this function to assign the 'text' variable with the text of the document and then populate the folder '/imgs' with the images in the document. 

I get this error: 

Traceback (most recent call last):
  File "doc2html.py", line 3, in <module>
    text = docx2txt.process("first-grade--consonants-and-digraphs--ng--king-who-swings--lesson-plan.docx", "/imgs") 
  File "/Library/Python/2.7/site-packages/docx2txt/docx2txt.py", line 103, in process
    with open(dst_fname, "w") as dst_f:
IOError: [Errno 2] No such file or directory: '/imgs/image3.png'

It appears the function is trying to read a file from where I would expect the file to be moved to.

**Comment by ankushshah89** [comment]
Its trying to write the images into the folder "/imgs" and  most likely, this folder couldn't be created because of permissions. If you are on linux system, you can replace "/imgs" with "/tmp/imgs".

**Comment by GarrettHartley** [comment]
Am I misunderstanding or does this show that this is not a permissions issue:

![screen shot 2016-04-08 at 3 05 48 pm](https://cloud.githubusercontent.com/assets/7108567/14397604/7ca24570-fd9b-11e5-80ea-92aad416f583.png)

**Comment by ankushshah89** [comment]
This is a permission issue. It says in the 7th line of your screenshot.

**Comment by GarrettHartley** [comment]
but not a permissions issue for the folder 'test'. It has everything readable and writeable. . . Sorry, I am confused, but maybe you can see how to fix this? Does the image3.png have a permissions issue? What should the permissions of the  output directory be if fully writeable and readable does not work? I am referring to the last line of the screenshot

**Comment by GarrettHartley** [comment]
Ok, thanks! I will try that out, unfortunately I can't right now.
