### ISSUE TITLE
excuse me,it can't run from python 

### ISSUE THREAD

**Issue by Mengqi777** [ankushshah89/python-docx2txt#7]
when I run my python code, here is the problem,
but I can run it from command

Traceback (most recent call last):
  File "D:/users/Python/readdocx/docx2txt.py", line 1, in <module>
    import docx2txt
  File "D:\users\Python\readdocx\docx2txt.py", line 3, in <module>
    print( docx2txt.process(r'D:\users\Python\readdocx\1.docx'))
AttributeError: module 'docx2txt' has no attribute 'process'

**Comment by ankushshah89** [comment]
Strange. Can you make sure it is importing the correct docx2txt?

```python
print docx2txt.__path__
```

**Comment by jvdzwaan** [comment]
I had the same issue. For me, it was due to the fact that I named my script `docx2txt`. Renaming it solved the problem.

**Comment by ankushshah89** [comment]
@Mengqi777 : It could be a similar reason for you like @jvdzwaan . I will close the issue now.
